name: Publish Package
on:
  release:
    types: [published] # Se activa al crear una Release en la web
  workflow_dispatch:
jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publishing is currently disabled."
